# Generated by Django 4.2.30 on 2026-04-29 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('mubawab', 'Mubawab'), ('sarouty', 'Sarouty'), ('avito', 'Avito'), ('sekna', 'Sekna'), ('mondinion', 'Mondinion'), ('autre', 'Autre')], db_index=True, max_length=50)),
                ('city', models.CharField(db_index=True, max_length=100, verbose_name='Ville')),
                ('district', models.CharField(blank=True, max_length=100, verbose_name='Quartier')),
                ('property_type', models.CharField(choices=[('apartment', 'Appartement'), ('villa', 'Villa / Maison'), ('riad', 'Riad'), ('hotel', 'Hôtel'), ('land', 'Terrain'), ('office', 'Bureau'), ('other', 'Autre')], db_index=True, max_length=50, verbose_name='Type')),
                ('title', models.CharField(blank=True, max_length=300, verbose_name='Titre')),
                ('price_mad', models.FloatField(db_index=True, verbose_name='Prix (MAD)')),
                ('price_per_m2_mad', models.FloatField(blank=True, null=True, verbose_name='Prix/m² (MAD)')),
                ('area_m2', models.FloatField(blank=True, null=True, verbose_name='Surface (m²)')),
                ('bedrooms', models.IntegerField(blank=True, null=True, verbose_name='Chambres')),
                ('bathrooms', models.IntegerField(blank=True, null=True, verbose_name='SDB')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('is_opportunity', models.BooleanField(default=False, verbose_name='Opportunité')),
                ('opportunity_score', models.FloatField(blank=True, null=True, verbose_name='Score opportunité')),
                ('price_category', models.CharField(blank=True, max_length=30, verbose_name='Catégorie prix')),
                ('url', models.URLField(blank=True, max_length=500)),
                ('scraped_at', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Bien immobilier',
                'verbose_name_plural': 'Biens immobiliers',
                'ordering': ['city', 'price_mad'],
            },
        ),
    ]
