# Generated by Django 4.2.30 on 2026-05-04 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='contact_agency',
            field=models.CharField(blank=True, max_length=200, verbose_name='Agence / Promoteur'),
        ),
        migrations.AddField(
            model_name='property',
            name='contact_email',
            field=models.CharField(blank=True, max_length=200, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='property',
            name='contact_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nom contact'),
        ),
        migrations.AddField(
            model_name='property',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Téléphone'),
        ),
        migrations.AddField(
            model_name='property',
            name='contact_phone2',
            field=models.CharField(blank=True, max_length=50, verbose_name='Téléphone 2'),
        ),
        migrations.AddField(
            model_name='property',
            name='contact_type',
            field=models.CharField(blank=True, choices=[('', 'Inconnu'), ('particulier', 'Particulier'), ('agence', 'Agence'), ('promoteur', 'Promoteur')], max_length=20, verbose_name='Type contact'),
        ),
        migrations.AlterField(
            model_name='property',
            name='source',
            field=models.CharField(choices=[('mubawab', 'Mubawab'), ('avito', 'Avito'), ('sarouty', 'Sarouty'), ('sekna', 'Sekna'), ('selectimmo', 'SelectImmo'), ('logiqueimmo', 'LogiqueImmo'), ('marocannonce', 'MarocAnnonce'), ('maisonmaroc', 'MaisonMaroc'), ('keurimmo', 'Keurimmo'), ('immobilier', 'Immobilier.ma'), ('autre', 'Autre')], db_index=True, max_length=50),
        ),
    ]
