# Generated by Django 4.2.30 on 2026-05-04 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_add_contact_fields_and_new_sources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='source',
            field=models.CharField(choices=[('mubawab', 'Mubawab'), ('avito', 'Avito'), ('sarouty', 'Sarouty'), ('agenz', 'Agenz'), ('marocannonces', 'MarocAnnonces'), ('masaken', 'Masaken'), ('logicimmo', 'LogicImmo'), ('bikhir', 'Bikhir'), ('autre', 'Autre')], db_index=True, max_length=50),
        ),
    ]
