# Generated by Django 4.2.30 on 2026-05-06 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_update_sources_v3'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='contact_whatsapp',
            field=models.URLField(blank=True, max_length=500, verbose_name='WhatsApp URL directe'),
        ),
    ]
