# Generated by Django 4.2.30 on 2026-05-06 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_add_contact_whatsapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='scraped_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date/Heure scraping'),
        ),
    ]
