# Generated by Django 5.2.17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_propertyimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='source',
            field=models.CharField(choices=[
                ('mubawab', 'Mubawab'), ('avito', 'Avito'), ('sarouty', 'Sarouty'),
                ('agenz', 'Agenz'), ('marocannonces', 'MarocAnnonces'),
                ('masaken', 'Masaken'), ('logicimmo', 'LogicImmo'),
                ('bikhir', 'Bikhir'), ('yakeey', 'Yakeey'), ('autre', 'Autre'),
            ], db_index=True, max_length=50),
        ),
    ]
